### ISSUE TITLE
Output? 

### ISSUE THREAD

**Issue by antithing** [Anttwo/MACARONS#1]
Hi, thanks for making this project available.

Is the input simply rgb images? 
What is the output? A color point cloud and camera poses?

Thanks!

**Comment by Anttwo** [comment]
Thank you for your interest!

As described in our paper, the complete model uses the following inputs:

- RGB images captured by the camera
- Corresponding camera poses
- A bounding box delimiting the scene to be explored and reconstructed

During the exploration process at each time step, the model applies three neural modules.

1. The first module predicts depth maps based on the previous RGB images and camera poses. These depth maps are then used to reconstruct and update a point cloud in real-time during exploration. The point cloud consists of points assumed to be located on the surface of the scene.
2. Using the reconstructed point cloud, the second module predicts and updates at each time step the occupancy probability across the entire volume of the scene. 
3. For camera poses that have not yet been visited, the third neural module estimates how this camera pose will increase the total coverage of the scene's surface. This module uses as inputs the occupancy probability field as well as features encoding the previous camera poses.

By iteratively applying these three neural modules, we are able to simultaneously explore and reconstruct large 3D scenes. Indeed, in the end, the full model produces a point cloud representing the surface of the scene as well as an occupancy field.
