### ISSUE TITLE
Which folder should I move the weights file to?

### ISSUE THREAD

**Issue by Jinqi-J** [Anttwo/MACARONS#2]
It seems that there are some weight files that are not declared in which folder they are to be placed.

**Comment by Anttwo** [comment]
The weights folder provided in our Google Drive ( https://drive.google.com/drive/u/4/folders/1wyc9_QFmcxOz4oerE8kCQ3I8LO5zioZL ) has the exact same structure as the ./weights folder in the repo. 

You just have to copy/paste the weight files from the Drive into the corresponding subfolders in the repo, i.e.:

```
weights
	macarons
		initialized_macarons.pth
		pretrained_macarons.pth
		trained_macarons_no_pretraining.pth
		trained_macarons.pth
	resnet
		depth_with_resnet_imagenet_weights.pth
	scone
		coverage_gain
			initialized_scone_vis.pth
			pretrained_scone_vis.pth
		occupancy
			initialized_scone_occ.pth
			pretrained_scone_occ.pth
```

The code should work if your weights folder looks like this. 
I hope this message answers well your question! If yes, I will close the issue.

**Comment by Jinqi-J** [comment]
Thanks for your reply, it helps me to clear up my confusion.
